version: '3.5'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: triturn
      MYSQL_PASSWORD: veljko
      MYSQL_ROOT_PASSWORD: veljko
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default
  www:
    build: .
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8080:80
    links:
      - db
    networks:
      - default

volumes:
  persistent: